services:
  db:
    image: postgres:14.0
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    networks:
      otus-highload-net:
    container_name: otus-highload-db
  web: &web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:${DOCKER_EXPOSE_PORT?80}:${GO_PORT?80}"
    depends_on:
      - db
    volumes:
      - .:/code/
    command: /runserver.sh
    restart: unless-stopped
    networks:
      otus-highload-net:
    container_name: otus-highload-web

networks:
  otus-highload-net:
