x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "250m"
    max-file: "4"

services:
  redis-counter:
    image: "redis/redis-stack:7.4.0-v0"
    ports:
      - 127.0.0.1:6579:6379
      - 127.0.0.1:8201:8001
    restart: always
    volumes:
      - ./.docker/redis-data:/data
    networks:
      - otus-highload-counter-net
      - otus-highload-messages-bridge
    logging: *default-logging

  web: &web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:${DOCKER_EXPOSE_PORT-80}:${GO_PORT-80}"
    volumes:
      - .:/code/
    command: /runserver.sh
    restart: unless-stopped
    networks:
      - otus-highload-counter-net
    container_name: otus-highload-counter-web
    logging: *default-logging

networks:
  otus-highload-counter-net:
  otus-highload-messages-bridge:
    external: True
